apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: react-frontend-template
  description: Production-ready Next.js frontend with Grafana Faro observability and enterprise patterns
spec:
  targets:
    - ./template.yaml
